/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SilkSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  serverUrl: "http://localhost:8080",
  apiToken: "",
  userId: ""
};

// src/sync.ts
var import_obsidian = require("obsidian");
async function runSync(app, settings) {
  if (!settings.serverUrl || !settings.apiToken || !settings.userId) {
    new import_obsidian.Notice("\u274C \u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u586B\u5199 Silk \u670D\u52A1\u5668\u5730\u5740\u3001Token \u548C\u7528\u6237 ID");
    return;
  }
  new import_obsidian.Notice("\u{1F504} Silk \u540C\u6B65\u4E2D...");
  try {
    const url = `${settings.serverUrl.replace(/\/+$/, "")}/api/obsidian/sync?userId=${encodeURIComponent(settings.userId)}`;
    const resp = await fetch(url, {
      headers: {
        Authorization: `Bearer ${settings.apiToken}`
      }
    });
    if (!resp.ok) {
      const text = await resp.text();
      new import_obsidian.Notice(`\u274C \u540C\u6B65\u5931\u8D25: HTTP ${resp.status}`);
      console.error("Silk sync error:", text);
      return;
    }
    const data = await resp.json();
    if (!data.success) {
      new import_obsidian.Notice("\u274C \u540C\u6B65\u5931\u8D25: \u670D\u52A1\u5668\u8FD4\u56DE\u9519\u8BEF");
      return;
    }
    let chatCount = 0;
    let kbCount = 0;
    for (const chat of data.chats) {
      await writeFile(app, chat.vaultPath, chat.markdown);
      chatCount++;
    }
    for (const entry of data.kbEntries) {
      await writeFile(app, entry.vaultPath, entry.markdown);
      kbCount++;
    }
    new import_obsidian.Notice(`\u2705 \u540C\u6B65\u5B8C\u6210: ${chatCount} \u4E2A\u7FA4\u804A, ${kbCount} \u6761 KB \u6761\u76EE`);
  } catch (e) {
    new import_obsidian.Notice(`\u274C \u540C\u6B65\u5931\u8D25: ${e.message}`);
    console.error("Silk sync error:", e);
  }
}
async function writeFile(app, vaultPath, content) {
  const parts = vaultPath.split("/");
  const fileName = parts.pop();
  let currentPath = "";
  for (const part of parts) {
    currentPath = currentPath ? `${currentPath}/${part}` : part;
    const folder = app.vault.getAbstractFileByPath(currentPath);
    if (!folder) {
      await app.vault.createFolder(currentPath);
    }
  }
  const existing = app.vault.getAbstractFileByPath(vaultPath);
  if (existing instanceof import_obsidian.TFile) {
    await app.vault.modify(existing, content);
  } else {
    await app.vault.create(vaultPath, content);
  }
}

// src/main.ts
var SilkSyncPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("cloud-download", "Silk \u4E00\u952E\u540C\u6B65", async () => {
      await runSync(this.app, this.settings);
    });
    this.addCommand({
      id: "silk-sync",
      name: "\u4E00\u952E\u540C\u6B65 Silk",
      callback: async () => {
        await runSync(this.app, this.settings);
      }
    });
    this.addSettingTab(new SilkSyncSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var SilkSyncSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Silk Sync \u8BBE\u7F6E" });
    new import_obsidian2.Setting(containerEl).setName("Silk \u670D\u52A1\u5668\u5730\u5740").setDesc("Silk \u540E\u7AEF\u7684\u5730\u5740\uFF0C\u4F8B\u5982 http://localhost:8080").addText(
      (text) => text.setPlaceholder("http://localhost:8080").setValue(this.plugin.settings.serverUrl).onChange(async (value) => {
        this.plugin.settings.serverUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("API Token").setDesc("\u4ECE Silk \u7528\u6237\u8BBE\u7F6E\u4E2D\u83B7\u53D6\u7684 API Token").addText((text) => {
      text.setPlaceholder("\u8F93\u5165 Token").setValue(this.plugin.settings.apiToken).onChange(async (value) => {
        this.plugin.settings.apiToken = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    new import_obsidian2.Setting(containerEl).setName("\u7528\u6237 ID").setDesc("\u4F60\u7684 Silk \u7528\u6237 ID").addText(
      (text) => text.setPlaceholder("\u8F93\u5165 userId").setValue(this.plugin.settings.userId).onChange(async (value) => {
        this.plugin.settings.userId = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
